-- Backfill and reconcile the canonical authorization catalog for every existing tenant.
-- Idempotent: safe for upgrade verification and restored databases.

INSERT INTO "permissions" ("id", "tenant_id", "name", "scope", "risk_level")
SELECT gen_random_uuid(), tenant."id", definition.name, definition.scope, definition.risk_level
FROM "tenants" AS tenant
CROSS JOIN (
  VALUES
    ('patient.view', 'tenant/branch', 'LOW'),
    ('patient.create', 'tenant/branch', 'LOW'),
    ('patient.update', 'tenant/branch', 'LOW'),
    ('patient.merge.request', 'tenant', 'MEDIUM'),
    ('patient.merge.approve', 'tenant', 'PRIVILEGED'),
    ('patient.self_service', 'tenant/user', 'LOW'),
    ('patient.portal.view_own', 'tenant/user', 'LOW'),
    ('patient.portal.appointment.view', 'tenant/user', 'LOW'),
    ('patient.portal.result.view', 'tenant/user', 'LOW'),
    ('patient.portal.billing.view', 'tenant/user', 'LOW'),
    ('patient.portal.message', 'tenant/user', 'LOW'),
    ('encounter.create', 'tenant/branch', 'LOW'),
    ('encounter.view', 'tenant/branch', 'LOW'),
    ('encounter.update', 'tenant/branch', 'LOW'),
    ('clinical_note.create', 'tenant/branch', 'LOW'),
    ('doctor.prescription.view', 'tenant/branch', 'LOW'),
    ('doctor.prescription.create', 'tenant/branch', 'LOW'),
    ('queue.view', 'tenant/branch', 'LOW'),
    ('queue.manage', 'tenant/branch', 'LOW'),
    ('order.view', 'tenant/branch', 'LOW'),
    ('order.create', 'tenant/branch', 'LOW'),
    ('order.cancel', 'tenant/branch', 'MEDIUM'),
    ('lab.result.view', 'tenant/branch/department', 'LOW'),
    ('lab.result.encode', 'tenant/branch/department', 'LOW'),
    ('lab.result.validate', 'tenant/branch/department', 'MEDIUM'),
    ('lab.result.approve', 'tenant/branch/department', 'HIGH'),
    ('lab.result.release', 'tenant/branch/department', 'HIGH'),
    ('lab.result.amend.request', 'tenant/branch', 'MEDIUM'),
    ('lab.specimen.receive', 'tenant/branch/department', 'LOW'),
    ('lab.critical.view', 'tenant/branch/department', 'LOW'),
    ('lab.critical.acknowledge', 'tenant/branch/department', 'MEDIUM'),
    ('lab.critical.escalate', 'tenant/branch/department', 'HIGH'),
    ('billing.invoice.view', 'tenant/branch', 'LOW'),
    ('billing.payment.create', 'tenant/branch/cashier-session', 'LOW'),
    ('billing.refund.request', 'tenant/branch', 'MEDIUM'),
    ('billing.refund.approve', 'tenant/branch', 'HIGH'),
    ('billing.payment.void.request', 'tenant/branch', 'MEDIUM'),
    ('billing.claim.view', 'tenant/branch', 'LOW'),
    ('billing.claim.create', 'tenant/branch', 'LOW'),
    ('billing.claim.process', 'tenant/branch', 'HIGH'),
    ('billing.reversal.apply', 'tenant/branch', 'HIGH'),
    ('inventory.item.view', 'tenant/branch', 'LOW'),
    ('inventory.item.create', 'tenant/branch', 'LOW'),
    ('inventory.item.update', 'tenant/branch', 'LOW'),
    ('inventory.item.deactivate', 'tenant/branch', 'MEDIUM'),
    ('inventory.stock.receive', 'tenant/branch', 'LOW'),
    ('inventory.stock.dispense', 'tenant/branch', 'LOW'),
    ('inventory.adjust.request', 'tenant/branch', 'MEDIUM'),
    ('inventory.adjust.approve', 'tenant/branch', 'HIGH'),
    ('catalog.service.view', 'tenant', 'LOW'),
    ('catalog.service.create', 'tenant', 'MEDIUM'),
    ('catalog.service.update', 'tenant', 'MEDIUM'),
    ('catalog.service.deactivate', 'tenant', 'HIGH'),
    ('catalog.manage', 'tenant', 'MEDIUM'),
    ('approval.request.create', 'tenant/branch', 'MEDIUM'),
    ('approval.request.view', 'tenant/branch', 'MEDIUM'),
    ('approval.request.process', 'tenant/branch', 'HIGH'),
    ('report.export', 'tenant/branch/role-scope', 'HIGH'),
    ('audit.view', 'tenant/branch/role-scope', 'HIGH'),
    ('audit.self', 'tenant/user', 'LOW'),
    ('audit.export', 'tenant/branch/role-scope', 'HIGH'),
    ('admin.health.view', 'tenant', 'HIGH'),
    ('admin.metrics.view', 'tenant', 'HIGH'),
    ('admin.user.view', 'tenant', 'HIGH'),
    ('admin.branch.view', 'tenant', 'HIGH'),
    ('admin.role.change', 'tenant/system', 'PRIVILEGED'),
    ('notification.view', 'tenant/user', 'LOW'),
    ('notification.manage', 'tenant/branch', 'MEDIUM'),
    ('integration.view', 'tenant', 'LOW'),
    ('compliance.audit.review', 'tenant', 'HIGH'),
    ('compliance.phi.monitor', 'tenant', 'HIGH'),
    ('compliance.report.export', 'tenant', 'HIGH'),
    ('it.system.view', 'tenant', 'LOW'),
    ('it.support.manage', 'tenant', 'MEDIUM'),
    ('it.ticket.view', 'tenant', 'LOW'),
    ('it.ticket.manage', 'tenant', 'MEDIUM'),
    ('hr.employee.view', 'tenant/branch', 'LOW'),
    ('hr.employee.manage', 'tenant/branch', 'MEDIUM'),
    ('hr.employee.status.change', 'tenant/branch', 'PRIVILEGED'),
    ('hr.leave.request.create_own', 'tenant/user', 'LOW'),
    ('hr.leave.request.view', 'tenant/branch', 'LOW'),
    ('hr.leave.request.approve', 'tenant/branch', 'MEDIUM'),
    ('hr.payroll.view', 'tenant/branch', 'HIGH'),
    ('procurement.request.view', 'tenant/branch', 'LOW'),
    ('procurement.request.create', 'tenant/branch', 'LOW'),
    ('procurement.request.approve', 'tenant/branch', 'HIGH'),
    ('procurement.supplier.view', 'tenant/branch', 'LOW'),
    ('procurement.supplier.manage', 'tenant', 'MEDIUM'),
    ('procurement.rfq.view', 'tenant/branch', 'LOW'),
    ('procurement.quote.view', 'tenant/branch', 'LOW'),
    ('procurement.po.view', 'tenant/branch', 'LOW'),
    ('procurement.po.create', 'tenant/branch', 'MEDIUM'),
    ('procurement.receiving.post', 'tenant/branch', 'MEDIUM'),
    ('procurement.vendor.performance.view', 'tenant/branch', 'LOW'),
    ('marketplace.buyer', 'tenant', 'LOW'),
    ('marketplace.supplier', 'tenant', 'LOW'),
    ('marketplace.admin', 'tenant', 'HIGH'),
    ('marketplace.buyer.view', 'tenant', 'LOW'),
    ('marketplace.supplier.view', 'tenant', 'LOW'),
    ('marketplace.supplier.manage_listing', 'tenant', 'MEDIUM'),
    ('marketplace.admin.view', 'tenant', 'HIGH'),
    ('marketplace.admin.manage', 'tenant', 'HIGH'),
    ('field_service.manage', 'tenant/branch', 'MEDIUM'),
    ('field_service.job.view', 'tenant/branch', 'LOW'),
    ('field_service.job.update', 'tenant/branch', 'MEDIUM'),
    ('field_service.job.assign', 'tenant/branch', 'MEDIUM'),
    ('field_service.installation.update', 'tenant/branch', 'MEDIUM'),
    ('field_service.delivery.proof_create', 'tenant/branch', 'MEDIUM'),
    ('field_service.maintenance.update', 'tenant/branch', 'MEDIUM'),
    ('fulfillment.view', 'tenant/branch', 'LOW'),
    ('fulfillment.update_status', 'tenant/branch', 'MEDIUM')
) AS definition(name, scope, risk_level)
ON CONFLICT ("tenant_id", "name") DO UPDATE
SET "scope" = EXCLUDED."scope",
    "risk_level" = EXCLUDED."risk_level";

INSERT INTO "roles" ("id", "tenant_id", "name", "status", "is_system")
SELECT gen_random_uuid(), tenant."id", definition.name, 'ACTIVE', TRUE
FROM "tenants" AS tenant
CROSS JOIN (
  VALUES
    ('Super Admin'),
    ('Branch Admin'),
    ('Doctor'),
    ('Nurse'),
    ('Cashier'),
    ('Finance'),
    ('Receptionist'),
    ('Lab Technician'),
    ('Med-Tech'),
    ('Pharmacist'),
    ('HR Staff'),
    ('HR Manager'),
    ('Procurement Agent'),
    ('Procurement Officer'),
    ('Procurement Manager'),
    ('IT Support'),
    ('Compliance Officer'),
    ('Field Technician'),
    ('Logistics Staff'),
    ('Service Manager'),
    ('Marketplace Buyer'),
    ('Customer'),
    ('Supplier'),
    ('Supplier Admin'),
    ('Marketplace Supplier'),
    ('Marketplace Admin'),
    ('Patient')
) AS definition(name)
ON CONFLICT ("tenant_id", "name") DO UPDATE
SET "status" = 'ACTIVE',
    "is_system" = TRUE,
    "archived_at" = NULL,
    "archived_reason" = NULL;

-- Built-in roles are immutable definitions. Remove stale grants before inserting
-- the canonical set so upgrades cannot leave accidental over-privilege behind.
WITH canonical_assignment(role_name, permission_name) AS (
  VALUES
    ('Super Admin', 'patient.view'),
    ('Super Admin', 'patient.create'),
    ('Super Admin', 'patient.update'),
    ('Super Admin', 'patient.merge.request'),
    ('Super Admin', 'patient.merge.approve'),
    ('Super Admin', 'patient.self_service'),
    ('Super Admin', 'patient.portal.view_own'),
    ('Super Admin', 'patient.portal.appointment.view'),
    ('Super Admin', 'patient.portal.result.view'),
    ('Super Admin', 'patient.portal.billing.view'),
    ('Super Admin', 'patient.portal.message'),
    ('Super Admin', 'encounter.create'),
    ('Super Admin', 'encounter.view'),
    ('Super Admin', 'encounter.update'),
    ('Super Admin', 'clinical_note.create'),
    ('Super Admin', 'doctor.prescription.view'),
    ('Super Admin', 'doctor.prescription.create'),
    ('Super Admin', 'queue.view'),
    ('Super Admin', 'queue.manage'),
    ('Super Admin', 'order.view'),
    ('Super Admin', 'order.create'),
    ('Super Admin', 'order.cancel'),
    ('Super Admin', 'lab.result.view'),
    ('Super Admin', 'lab.result.encode'),
    ('Super Admin', 'lab.result.validate'),
    ('Super Admin', 'lab.result.approve'),
    ('Super Admin', 'lab.result.release'),
    ('Super Admin', 'lab.result.amend.request'),
    ('Super Admin', 'lab.specimen.receive'),
    ('Super Admin', 'lab.critical.view'),
    ('Super Admin', 'lab.critical.acknowledge'),
    ('Super Admin', 'lab.critical.escalate'),
    ('Super Admin', 'billing.invoice.view'),
    ('Super Admin', 'billing.payment.create'),
    ('Super Admin', 'billing.refund.request'),
    ('Super Admin', 'billing.refund.approve'),
    ('Super Admin', 'billing.payment.void.request'),
    ('Super Admin', 'billing.claim.view'),
    ('Super Admin', 'billing.claim.create'),
    ('Super Admin', 'billing.claim.process'),
    ('Super Admin', 'billing.reversal.apply'),
    ('Super Admin', 'inventory.item.view'),
    ('Super Admin', 'inventory.item.create'),
    ('Super Admin', 'inventory.item.update'),
    ('Super Admin', 'inventory.item.deactivate'),
    ('Super Admin', 'inventory.stock.receive'),
    ('Super Admin', 'inventory.stock.dispense'),
    ('Super Admin', 'inventory.adjust.request'),
    ('Super Admin', 'inventory.adjust.approve'),
    ('Super Admin', 'catalog.service.view'),
    ('Super Admin', 'catalog.service.create'),
    ('Super Admin', 'catalog.service.update'),
    ('Super Admin', 'catalog.service.deactivate'),
    ('Super Admin', 'catalog.manage'),
    ('Super Admin', 'approval.request.create'),
    ('Super Admin', 'approval.request.view'),
    ('Super Admin', 'approval.request.process'),
    ('Super Admin', 'report.export'),
    ('Super Admin', 'audit.view'),
    ('Super Admin', 'audit.self'),
    ('Super Admin', 'audit.export'),
    ('Super Admin', 'admin.health.view'),
    ('Super Admin', 'admin.metrics.view'),
    ('Super Admin', 'admin.user.view'),
    ('Super Admin', 'admin.branch.view'),
    ('Super Admin', 'admin.role.change'),
    ('Super Admin', 'notification.view'),
    ('Super Admin', 'notification.manage'),
    ('Super Admin', 'integration.view'),
    ('Super Admin', 'compliance.audit.review'),
    ('Super Admin', 'compliance.phi.monitor'),
    ('Super Admin', 'compliance.report.export'),
    ('Super Admin', 'it.system.view'),
    ('Super Admin', 'it.support.manage'),
    ('Super Admin', 'it.ticket.view'),
    ('Super Admin', 'it.ticket.manage'),
    ('Super Admin', 'hr.employee.view'),
    ('Super Admin', 'hr.employee.manage'),
    ('Super Admin', 'hr.employee.status.change'),
    ('Super Admin', 'hr.leave.request.create_own'),
    ('Super Admin', 'hr.leave.request.view'),
    ('Super Admin', 'hr.leave.request.approve'),
    ('Super Admin', 'hr.payroll.view'),
    ('Super Admin', 'procurement.request.view'),
    ('Super Admin', 'procurement.request.create'),
    ('Super Admin', 'procurement.request.approve'),
    ('Super Admin', 'procurement.supplier.view'),
    ('Super Admin', 'procurement.supplier.manage'),
    ('Super Admin', 'procurement.rfq.view'),
    ('Super Admin', 'procurement.quote.view'),
    ('Super Admin', 'procurement.po.view'),
    ('Super Admin', 'procurement.po.create'),
    ('Super Admin', 'procurement.receiving.post'),
    ('Super Admin', 'procurement.vendor.performance.view'),
    ('Super Admin', 'marketplace.buyer'),
    ('Super Admin', 'marketplace.supplier'),
    ('Super Admin', 'marketplace.admin'),
    ('Super Admin', 'marketplace.buyer.view'),
    ('Super Admin', 'marketplace.supplier.view'),
    ('Super Admin', 'marketplace.supplier.manage_listing'),
    ('Super Admin', 'marketplace.admin.view'),
    ('Super Admin', 'marketplace.admin.manage'),
    ('Super Admin', 'field_service.manage'),
    ('Super Admin', 'field_service.job.view'),
    ('Super Admin', 'field_service.job.update'),
    ('Super Admin', 'field_service.job.assign'),
    ('Super Admin', 'field_service.installation.update'),
    ('Super Admin', 'field_service.delivery.proof_create'),
    ('Super Admin', 'field_service.maintenance.update'),
    ('Super Admin', 'fulfillment.view'),
    ('Super Admin', 'fulfillment.update_status'),
    ('Branch Admin', 'patient.view'),
    ('Branch Admin', 'patient.create'),
    ('Branch Admin', 'patient.update'),
    ('Branch Admin', 'encounter.create'),
    ('Branch Admin', 'encounter.view'),
    ('Branch Admin', 'encounter.update'),
    ('Branch Admin', 'queue.view'),
    ('Branch Admin', 'order.view'),
    ('Branch Admin', 'audit.self'),
    ('Branch Admin', 'notification.view'),
    ('Branch Admin', 'queue.manage'),
    ('Branch Admin', 'order.create'),
    ('Branch Admin', 'order.cancel'),
    ('Branch Admin', 'lab.result.view'),
    ('Branch Admin', 'lab.result.encode'),
    ('Branch Admin', 'lab.result.validate'),
    ('Branch Admin', 'lab.result.approve'),
    ('Branch Admin', 'lab.result.release'),
    ('Branch Admin', 'lab.specimen.receive'),
    ('Branch Admin', 'lab.critical.view'),
    ('Branch Admin', 'billing.invoice.view'),
    ('Branch Admin', 'billing.payment.create'),
    ('Branch Admin', 'billing.refund.request'),
    ('Branch Admin', 'billing.payment.void.request'),
    ('Branch Admin', 'billing.claim.view'),
    ('Branch Admin', 'billing.claim.create'),
    ('Branch Admin', 'inventory.item.view'),
    ('Branch Admin', 'inventory.item.create'),
    ('Branch Admin', 'inventory.item.update'),
    ('Branch Admin', 'inventory.stock.receive'),
    ('Branch Admin', 'inventory.stock.dispense'),
    ('Branch Admin', 'inventory.adjust.request'),
    ('Branch Admin', 'catalog.service.view'),
    ('Branch Admin', 'approval.request.create'),
    ('Branch Admin', 'approval.request.view'),
    ('Branch Admin', 'approval.request.process'),
    ('Branch Admin', 'report.export'),
    ('Branch Admin', 'audit.view'),
    ('Branch Admin', 'hr.employee.view'),
    ('Branch Admin', 'hr.employee.manage'),
    ('Branch Admin', 'procurement.request.view'),
    ('Branch Admin', 'procurement.request.create'),
    ('Branch Admin', 'procurement.supplier.view'),
    ('Branch Admin', 'procurement.rfq.view'),
    ('Branch Admin', 'procurement.quote.view'),
    ('Branch Admin', 'procurement.po.view'),
    ('Branch Admin', 'procurement.receiving.post'),
    ('Branch Admin', 'procurement.vendor.performance.view'),
    ('Branch Admin', 'field_service.manage'),
    ('Branch Admin', 'field_service.job.view'),
    ('Branch Admin', 'field_service.job.update'),
    ('Branch Admin', 'field_service.installation.update'),
    ('Branch Admin', 'field_service.delivery.proof_create'),
    ('Branch Admin', 'field_service.maintenance.update'),
    ('Branch Admin', 'audit.self'),
    ('Branch Admin', 'notification.view'),
    ('Branch Admin', 'field_service.job.assign'),
    ('Branch Admin', 'fulfillment.view'),
    ('Branch Admin', 'fulfillment.update_status'),
    ('Branch Admin', 'integration.view'),
    ('Branch Admin', 'admin.user.view'),
    ('Branch Admin', 'admin.branch.view'),
    ('Branch Admin', 'hr.leave.request.view'),
    ('Branch Admin', 'hr.leave.request.approve'),
    ('Branch Admin', 'hr.leave.request.create_own'),
    ('Doctor', 'patient.view'),
    ('Doctor', 'patient.create'),
    ('Doctor', 'patient.update'),
    ('Doctor', 'encounter.create'),
    ('Doctor', 'encounter.view'),
    ('Doctor', 'encounter.update'),
    ('Doctor', 'queue.view'),
    ('Doctor', 'order.view'),
    ('Doctor', 'audit.self'),
    ('Doctor', 'notification.view'),
    ('Doctor', 'queue.manage'),
    ('Doctor', 'order.create'),
    ('Doctor', 'lab.result.view'),
    ('Doctor', 'clinical_note.create'),
    ('Doctor', 'doctor.prescription.view'),
    ('Doctor', 'doctor.prescription.create'),
    ('Doctor', 'hr.leave.request.create_own'),
    ('Doctor', 'hr.leave.request.view'),
    ('Nurse', 'patient.view'),
    ('Nurse', 'patient.create'),
    ('Nurse', 'patient.update'),
    ('Nurse', 'encounter.create'),
    ('Nurse', 'encounter.view'),
    ('Nurse', 'encounter.update'),
    ('Nurse', 'queue.view'),
    ('Nurse', 'order.view'),
    ('Nurse', 'audit.self'),
    ('Nurse', 'notification.view'),
    ('Nurse', 'queue.manage'),
    ('Nurse', 'order.create'),
    ('Nurse', 'lab.result.view'),
    ('Nurse', 'lab.specimen.receive'),
    ('Nurse', 'lab.critical.view'),
    ('Nurse', 'hr.leave.request.create_own'),
    ('Nurse', 'hr.leave.request.view'),
    ('Cashier', 'patient.view'),
    ('Cashier', 'order.view'),
    ('Cashier', 'billing.invoice.view'),
    ('Cashier', 'billing.payment.create'),
    ('Cashier', 'billing.refund.request'),
    ('Cashier', 'billing.payment.void.request'),
    ('Cashier', 'billing.claim.view'),
    ('Cashier', 'billing.claim.create'),
    ('Cashier', 'approval.request.create'),
    ('Cashier', 'approval.request.view'),
    ('Cashier', 'audit.self'),
    ('Cashier', 'notification.view'),
    ('Finance', 'patient.view'),
    ('Finance', 'order.view'),
    ('Finance', 'billing.invoice.view'),
    ('Finance', 'billing.payment.create'),
    ('Finance', 'billing.refund.request'),
    ('Finance', 'billing.refund.approve'),
    ('Finance', 'billing.payment.void.request'),
    ('Finance', 'billing.claim.view'),
    ('Finance', 'billing.claim.create'),
    ('Finance', 'billing.claim.process'),
    ('Finance', 'billing.reversal.apply'),
    ('Finance', 'approval.request.view'),
    ('Finance', 'approval.request.process'),
    ('Finance', 'report.export'),
    ('Finance', 'audit.self'),
    ('Receptionist', 'patient.view'),
    ('Receptionist', 'patient.create'),
    ('Receptionist', 'patient.update'),
    ('Receptionist', 'queue.view'),
    ('Receptionist', 'queue.manage'),
    ('Receptionist', 'audit.self'),
    ('Lab Technician', 'patient.view'),
    ('Lab Technician', 'order.view'),
    ('Lab Technician', 'lab.result.view'),
    ('Lab Technician', 'lab.result.encode'),
    ('Lab Technician', 'lab.result.validate'),
    ('Lab Technician', 'lab.specimen.receive'),
    ('Lab Technician', 'lab.critical.view'),
    ('Lab Technician', 'lab.critical.acknowledge'),
    ('Lab Technician', 'audit.self'),
    ('Med-Tech', 'patient.view'),
    ('Med-Tech', 'order.view'),
    ('Med-Tech', 'lab.result.view'),
    ('Med-Tech', 'lab.result.encode'),
    ('Med-Tech', 'lab.result.validate'),
    ('Med-Tech', 'lab.result.approve'),
    ('Med-Tech', 'lab.result.release'),
    ('Med-Tech', 'lab.result.amend.request'),
    ('Med-Tech', 'lab.specimen.receive'),
    ('Med-Tech', 'lab.critical.view'),
    ('Med-Tech', 'lab.critical.acknowledge'),
    ('Med-Tech', 'lab.critical.escalate'),
    ('Med-Tech', 'audit.self'),
    ('Pharmacist', 'patient.view'),
    ('Pharmacist', 'order.view'),
    ('Pharmacist', 'inventory.item.view'),
    ('Pharmacist', 'inventory.item.create'),
    ('Pharmacist', 'inventory.item.update'),
    ('Pharmacist', 'inventory.stock.receive'),
    ('Pharmacist', 'inventory.stock.dispense'),
    ('Pharmacist', 'inventory.adjust.request'),
    ('Pharmacist', 'audit.self'),
    ('HR Staff', 'hr.employee.view'),
    ('HR Staff', 'hr.employee.manage'),
    ('HR Staff', 'hr.employee.status.change'),
    ('HR Staff', 'hr.leave.request.view'),
    ('HR Staff', 'hr.leave.request.approve'),
    ('HR Staff', 'hr.leave.request.create_own'),
    ('HR Staff', 'audit.self'),
    ('HR Manager', 'hr.employee.view'),
    ('HR Manager', 'hr.employee.manage'),
    ('HR Manager', 'hr.employee.status.change'),
    ('HR Manager', 'hr.payroll.view'),
    ('HR Manager', 'hr.leave.request.view'),
    ('HR Manager', 'hr.leave.request.approve'),
    ('HR Manager', 'hr.leave.request.create_own'),
    ('HR Manager', 'report.export'),
    ('HR Manager', 'audit.self'),
    ('Procurement Agent', 'procurement.request.view'),
    ('Procurement Agent', 'procurement.request.create'),
    ('Procurement Agent', 'procurement.supplier.view'),
    ('Procurement Agent', 'procurement.rfq.view'),
    ('Procurement Agent', 'procurement.quote.view'),
    ('Procurement Agent', 'procurement.po.view'),
    ('Procurement Agent', 'procurement.receiving.post'),
    ('Procurement Agent', 'procurement.vendor.performance.view'),
    ('Procurement Agent', 'inventory.item.view'),
    ('Procurement Agent', 'audit.self'),
    ('Procurement Officer', 'procurement.request.view'),
    ('Procurement Officer', 'procurement.request.create'),
    ('Procurement Officer', 'procurement.supplier.view'),
    ('Procurement Officer', 'procurement.supplier.manage'),
    ('Procurement Officer', 'procurement.rfq.view'),
    ('Procurement Officer', 'procurement.quote.view'),
    ('Procurement Officer', 'procurement.po.view'),
    ('Procurement Officer', 'procurement.po.create'),
    ('Procurement Officer', 'procurement.receiving.post'),
    ('Procurement Officer', 'procurement.vendor.performance.view'),
    ('Procurement Officer', 'inventory.item.view'),
    ('Procurement Officer', 'audit.self'),
    ('Procurement Manager', 'procurement.request.view'),
    ('Procurement Manager', 'procurement.request.create'),
    ('Procurement Manager', 'procurement.request.approve'),
    ('Procurement Manager', 'procurement.supplier.view'),
    ('Procurement Manager', 'procurement.supplier.manage'),
    ('Procurement Manager', 'procurement.rfq.view'),
    ('Procurement Manager', 'procurement.quote.view'),
    ('Procurement Manager', 'procurement.po.view'),
    ('Procurement Manager', 'procurement.po.create'),
    ('Procurement Manager', 'procurement.receiving.post'),
    ('Procurement Manager', 'procurement.vendor.performance.view'),
    ('Procurement Manager', 'inventory.item.view'),
    ('Procurement Manager', 'report.export'),
    ('Procurement Manager', 'audit.self'),
    ('IT Support', 'it.system.view'),
    ('IT Support', 'it.support.manage'),
    ('IT Support', 'it.ticket.view'),
    ('IT Support', 'it.ticket.manage'),
    ('IT Support', 'notification.view'),
    ('IT Support', 'notification.manage'),
    ('IT Support', 'integration.view'),
    ('IT Support', 'audit.view'),
    ('IT Support', 'audit.self'),
    ('Compliance Officer', 'compliance.audit.review'),
    ('Compliance Officer', 'compliance.phi.monitor'),
    ('Compliance Officer', 'compliance.report.export'),
    ('Compliance Officer', 'audit.view'),
    ('Compliance Officer', 'audit.self'),
    ('Compliance Officer', 'audit.export'),
    ('Compliance Officer', 'report.export'),
    ('Compliance Officer', 'notification.view'),
    ('Field Technician', 'field_service.manage'),
    ('Field Technician', 'field_service.job.view'),
    ('Field Technician', 'field_service.job.update'),
    ('Field Technician', 'field_service.installation.update'),
    ('Field Technician', 'field_service.delivery.proof_create'),
    ('Field Technician', 'field_service.maintenance.update'),
    ('Field Technician', 'audit.self'),
    ('Field Technician', 'notification.view'),
    ('Logistics Staff', 'field_service.manage'),
    ('Logistics Staff', 'field_service.job.view'),
    ('Logistics Staff', 'field_service.job.update'),
    ('Logistics Staff', 'field_service.installation.update'),
    ('Logistics Staff', 'field_service.delivery.proof_create'),
    ('Logistics Staff', 'field_service.maintenance.update'),
    ('Logistics Staff', 'audit.self'),
    ('Logistics Staff', 'notification.view'),
    ('Logistics Staff', 'fulfillment.view'),
    ('Logistics Staff', 'fulfillment.update_status'),
    ('Service Manager', 'field_service.manage'),
    ('Service Manager', 'field_service.job.view'),
    ('Service Manager', 'field_service.job.update'),
    ('Service Manager', 'field_service.installation.update'),
    ('Service Manager', 'field_service.delivery.proof_create'),
    ('Service Manager', 'field_service.maintenance.update'),
    ('Service Manager', 'audit.self'),
    ('Service Manager', 'notification.view'),
    ('Service Manager', 'field_service.job.assign'),
    ('Service Manager', 'fulfillment.view'),
    ('Service Manager', 'fulfillment.update_status'),
    ('Service Manager', 'report.export'),
    ('Marketplace Buyer', 'marketplace.buyer'),
    ('Marketplace Buyer', 'marketplace.buyer.view'),
    ('Marketplace Buyer', 'audit.self'),
    ('Customer', 'marketplace.buyer'),
    ('Customer', 'marketplace.buyer.view'),
    ('Customer', 'audit.self'),
    ('Supplier', 'marketplace.supplier'),
    ('Supplier', 'marketplace.supplier.view'),
    ('Supplier', 'marketplace.supplier.manage_listing'),
    ('Supplier', 'audit.self'),
    ('Supplier Admin', 'marketplace.supplier'),
    ('Supplier Admin', 'marketplace.supplier.view'),
    ('Supplier Admin', 'marketplace.supplier.manage_listing'),
    ('Supplier Admin', 'audit.self'),
    ('Marketplace Supplier', 'marketplace.supplier'),
    ('Marketplace Supplier', 'marketplace.supplier.view'),
    ('Marketplace Supplier', 'marketplace.supplier.manage_listing'),
    ('Marketplace Supplier', 'audit.self'),
    ('Marketplace Admin', 'marketplace.admin'),
    ('Marketplace Admin', 'marketplace.admin.view'),
    ('Marketplace Admin', 'marketplace.admin.manage'),
    ('Marketplace Admin', 'integration.view'),
    ('Marketplace Admin', 'audit.self'),
    ('Patient', 'patient.self_service'),
    ('Patient', 'patient.portal.view_own'),
    ('Patient', 'patient.portal.appointment.view'),
    ('Patient', 'patient.portal.result.view'),
    ('Patient', 'patient.portal.billing.view'),
    ('Patient', 'patient.portal.message'),
    ('Patient', 'audit.self')
)
DELETE FROM "role_permissions" AS role_permission
USING "roles" AS role
WHERE role_permission."role_id" = role."id"
  AND role."is_system" = TRUE
  AND role."name" IN ('Super Admin', 'Branch Admin', 'Doctor', 'Nurse', 'Cashier', 'Finance', 'Receptionist', 'Lab Technician', 'Med-Tech', 'Pharmacist', 'HR Staff', 'HR Manager', 'Procurement Agent', 'Procurement Officer', 'Procurement Manager', 'IT Support', 'Compliance Officer', 'Field Technician', 'Logistics Staff', 'Service Manager', 'Marketplace Buyer', 'Customer', 'Supplier', 'Supplier Admin', 'Marketplace Supplier', 'Marketplace Admin', 'Patient')
  AND NOT EXISTS (
    SELECT 1
    FROM canonical_assignment AS assignment
    JOIN "permissions" AS permission
      ON permission."tenant_id" = role."tenant_id"
     AND permission."name" = assignment.permission_name
    WHERE assignment.role_name = role."name"
      AND permission."id" = role_permission."permission_id"
  );

INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT role."id", permission."id"
FROM (
  VALUES
    ('Super Admin', 'patient.view'),
    ('Super Admin', 'patient.create'),
    ('Super Admin', 'patient.update'),
    ('Super Admin', 'patient.merge.request'),
    ('Super Admin', 'patient.merge.approve'),
    ('Super Admin', 'patient.self_service'),
    ('Super Admin', 'patient.portal.view_own'),
    ('Super Admin', 'patient.portal.appointment.view'),
    ('Super Admin', 'patient.portal.result.view'),
    ('Super Admin', 'patient.portal.billing.view'),
    ('Super Admin', 'patient.portal.message'),
    ('Super Admin', 'encounter.create'),
    ('Super Admin', 'encounter.view'),
    ('Super Admin', 'encounter.update'),
    ('Super Admin', 'clinical_note.create'),
    ('Super Admin', 'doctor.prescription.view'),
    ('Super Admin', 'doctor.prescription.create'),
    ('Super Admin', 'queue.view'),
    ('Super Admin', 'queue.manage'),
    ('Super Admin', 'order.view'),
    ('Super Admin', 'order.create'),
    ('Super Admin', 'order.cancel'),
    ('Super Admin', 'lab.result.view'),
    ('Super Admin', 'lab.result.encode'),
    ('Super Admin', 'lab.result.validate'),
    ('Super Admin', 'lab.result.approve'),
    ('Super Admin', 'lab.result.release'),
    ('Super Admin', 'lab.result.amend.request'),
    ('Super Admin', 'lab.specimen.receive'),
    ('Super Admin', 'lab.critical.view'),
    ('Super Admin', 'lab.critical.acknowledge'),
    ('Super Admin', 'lab.critical.escalate'),
    ('Super Admin', 'billing.invoice.view'),
    ('Super Admin', 'billing.payment.create'),
    ('Super Admin', 'billing.refund.request'),
    ('Super Admin', 'billing.refund.approve'),
    ('Super Admin', 'billing.payment.void.request'),
    ('Super Admin', 'billing.claim.view'),
    ('Super Admin', 'billing.claim.create'),
    ('Super Admin', 'billing.claim.process'),
    ('Super Admin', 'billing.reversal.apply'),
    ('Super Admin', 'inventory.item.view'),
    ('Super Admin', 'inventory.item.create'),
    ('Super Admin', 'inventory.item.update'),
    ('Super Admin', 'inventory.item.deactivate'),
    ('Super Admin', 'inventory.stock.receive'),
    ('Super Admin', 'inventory.stock.dispense'),
    ('Super Admin', 'inventory.adjust.request'),
    ('Super Admin', 'inventory.adjust.approve'),
    ('Super Admin', 'catalog.service.view'),
    ('Super Admin', 'catalog.service.create'),
    ('Super Admin', 'catalog.service.update'),
    ('Super Admin', 'catalog.service.deactivate'),
    ('Super Admin', 'catalog.manage'),
    ('Super Admin', 'approval.request.create'),
    ('Super Admin', 'approval.request.view'),
    ('Super Admin', 'approval.request.process'),
    ('Super Admin', 'report.export'),
    ('Super Admin', 'audit.view'),
    ('Super Admin', 'audit.self'),
    ('Super Admin', 'audit.export'),
    ('Super Admin', 'admin.health.view'),
    ('Super Admin', 'admin.metrics.view'),
    ('Super Admin', 'admin.user.view'),
    ('Super Admin', 'admin.branch.view'),
    ('Super Admin', 'admin.role.change'),
    ('Super Admin', 'notification.view'),
    ('Super Admin', 'notification.manage'),
    ('Super Admin', 'integration.view'),
    ('Super Admin', 'compliance.audit.review'),
    ('Super Admin', 'compliance.phi.monitor'),
    ('Super Admin', 'compliance.report.export'),
    ('Super Admin', 'it.system.view'),
    ('Super Admin', 'it.support.manage'),
    ('Super Admin', 'it.ticket.view'),
    ('Super Admin', 'it.ticket.manage'),
    ('Super Admin', 'hr.employee.view'),
    ('Super Admin', 'hr.employee.manage'),
    ('Super Admin', 'hr.employee.status.change'),
    ('Super Admin', 'hr.leave.request.create_own'),
    ('Super Admin', 'hr.leave.request.view'),
    ('Super Admin', 'hr.leave.request.approve'),
    ('Super Admin', 'hr.payroll.view'),
    ('Super Admin', 'procurement.request.view'),
    ('Super Admin', 'procurement.request.create'),
    ('Super Admin', 'procurement.request.approve'),
    ('Super Admin', 'procurement.supplier.view'),
    ('Super Admin', 'procurement.supplier.manage'),
    ('Super Admin', 'procurement.rfq.view'),
    ('Super Admin', 'procurement.quote.view'),
    ('Super Admin', 'procurement.po.view'),
    ('Super Admin', 'procurement.po.create'),
    ('Super Admin', 'procurement.receiving.post'),
    ('Super Admin', 'procurement.vendor.performance.view'),
    ('Super Admin', 'marketplace.buyer'),
    ('Super Admin', 'marketplace.supplier'),
    ('Super Admin', 'marketplace.admin'),
    ('Super Admin', 'marketplace.buyer.view'),
    ('Super Admin', 'marketplace.supplier.view'),
    ('Super Admin', 'marketplace.supplier.manage_listing'),
    ('Super Admin', 'marketplace.admin.view'),
    ('Super Admin', 'marketplace.admin.manage'),
    ('Super Admin', 'field_service.manage'),
    ('Super Admin', 'field_service.job.view'),
    ('Super Admin', 'field_service.job.update'),
    ('Super Admin', 'field_service.job.assign'),
    ('Super Admin', 'field_service.installation.update'),
    ('Super Admin', 'field_service.delivery.proof_create'),
    ('Super Admin', 'field_service.maintenance.update'),
    ('Super Admin', 'fulfillment.view'),
    ('Super Admin', 'fulfillment.update_status'),
    ('Branch Admin', 'patient.view'),
    ('Branch Admin', 'patient.create'),
    ('Branch Admin', 'patient.update'),
    ('Branch Admin', 'encounter.create'),
    ('Branch Admin', 'encounter.view'),
    ('Branch Admin', 'encounter.update'),
    ('Branch Admin', 'queue.view'),
    ('Branch Admin', 'order.view'),
    ('Branch Admin', 'audit.self'),
    ('Branch Admin', 'notification.view'),
    ('Branch Admin', 'queue.manage'),
    ('Branch Admin', 'order.create'),
    ('Branch Admin', 'order.cancel'),
    ('Branch Admin', 'lab.result.view'),
    ('Branch Admin', 'lab.result.encode'),
    ('Branch Admin', 'lab.result.validate'),
    ('Branch Admin', 'lab.result.approve'),
    ('Branch Admin', 'lab.result.release'),
    ('Branch Admin', 'lab.specimen.receive'),
    ('Branch Admin', 'lab.critical.view'),
    ('Branch Admin', 'billing.invoice.view'),
    ('Branch Admin', 'billing.payment.create'),
    ('Branch Admin', 'billing.refund.request'),
    ('Branch Admin', 'billing.payment.void.request'),
    ('Branch Admin', 'billing.claim.view'),
    ('Branch Admin', 'billing.claim.create'),
    ('Branch Admin', 'inventory.item.view'),
    ('Branch Admin', 'inventory.item.create'),
    ('Branch Admin', 'inventory.item.update'),
    ('Branch Admin', 'inventory.stock.receive'),
    ('Branch Admin', 'inventory.stock.dispense'),
    ('Branch Admin', 'inventory.adjust.request'),
    ('Branch Admin', 'catalog.service.view'),
    ('Branch Admin', 'approval.request.create'),
    ('Branch Admin', 'approval.request.view'),
    ('Branch Admin', 'approval.request.process'),
    ('Branch Admin', 'report.export'),
    ('Branch Admin', 'audit.view'),
    ('Branch Admin', 'hr.employee.view'),
    ('Branch Admin', 'hr.employee.manage'),
    ('Branch Admin', 'procurement.request.view'),
    ('Branch Admin', 'procurement.request.create'),
    ('Branch Admin', 'procurement.supplier.view'),
    ('Branch Admin', 'procurement.rfq.view'),
    ('Branch Admin', 'procurement.quote.view'),
    ('Branch Admin', 'procurement.po.view'),
    ('Branch Admin', 'procurement.receiving.post'),
    ('Branch Admin', 'procurement.vendor.performance.view'),
    ('Branch Admin', 'field_service.manage'),
    ('Branch Admin', 'field_service.job.view'),
    ('Branch Admin', 'field_service.job.update'),
    ('Branch Admin', 'field_service.installation.update'),
    ('Branch Admin', 'field_service.delivery.proof_create'),
    ('Branch Admin', 'field_service.maintenance.update'),
    ('Branch Admin', 'audit.self'),
    ('Branch Admin', 'notification.view'),
    ('Branch Admin', 'field_service.job.assign'),
    ('Branch Admin', 'fulfillment.view'),
    ('Branch Admin', 'fulfillment.update_status'),
    ('Branch Admin', 'integration.view'),
    ('Branch Admin', 'admin.user.view'),
    ('Branch Admin', 'admin.branch.view'),
    ('Branch Admin', 'hr.leave.request.view'),
    ('Branch Admin', 'hr.leave.request.approve'),
    ('Branch Admin', 'hr.leave.request.create_own'),
    ('Doctor', 'patient.view'),
    ('Doctor', 'patient.create'),
    ('Doctor', 'patient.update'),
    ('Doctor', 'encounter.create'),
    ('Doctor', 'encounter.view'),
    ('Doctor', 'encounter.update'),
    ('Doctor', 'queue.view'),
    ('Doctor', 'order.view'),
    ('Doctor', 'audit.self'),
    ('Doctor', 'notification.view'),
    ('Doctor', 'queue.manage'),
    ('Doctor', 'order.create'),
    ('Doctor', 'lab.result.view'),
    ('Doctor', 'clinical_note.create'),
    ('Doctor', 'doctor.prescription.view'),
    ('Doctor', 'doctor.prescription.create'),
    ('Doctor', 'hr.leave.request.create_own'),
    ('Doctor', 'hr.leave.request.view'),
    ('Nurse', 'patient.view'),
    ('Nurse', 'patient.create'),
    ('Nurse', 'patient.update'),
    ('Nurse', 'encounter.create'),
    ('Nurse', 'encounter.view'),
    ('Nurse', 'encounter.update'),
    ('Nurse', 'queue.view'),
    ('Nurse', 'order.view'),
    ('Nurse', 'audit.self'),
    ('Nurse', 'notification.view'),
    ('Nurse', 'queue.manage'),
    ('Nurse', 'order.create'),
    ('Nurse', 'lab.result.view'),
    ('Nurse', 'lab.specimen.receive'),
    ('Nurse', 'lab.critical.view'),
    ('Nurse', 'hr.leave.request.create_own'),
    ('Nurse', 'hr.leave.request.view'),
    ('Cashier', 'patient.view'),
    ('Cashier', 'order.view'),
    ('Cashier', 'billing.invoice.view'),
    ('Cashier', 'billing.payment.create'),
    ('Cashier', 'billing.refund.request'),
    ('Cashier', 'billing.payment.void.request'),
    ('Cashier', 'billing.claim.view'),
    ('Cashier', 'billing.claim.create'),
    ('Cashier', 'approval.request.create'),
    ('Cashier', 'approval.request.view'),
    ('Cashier', 'audit.self'),
    ('Cashier', 'notification.view'),
    ('Finance', 'patient.view'),
    ('Finance', 'order.view'),
    ('Finance', 'billing.invoice.view'),
    ('Finance', 'billing.payment.create'),
    ('Finance', 'billing.refund.request'),
    ('Finance', 'billing.refund.approve'),
    ('Finance', 'billing.payment.void.request'),
    ('Finance', 'billing.claim.view'),
    ('Finance', 'billing.claim.create'),
    ('Finance', 'billing.claim.process'),
    ('Finance', 'billing.reversal.apply'),
    ('Finance', 'approval.request.view'),
    ('Finance', 'approval.request.process'),
    ('Finance', 'report.export'),
    ('Finance', 'audit.self'),
    ('Receptionist', 'patient.view'),
    ('Receptionist', 'patient.create'),
    ('Receptionist', 'patient.update'),
    ('Receptionist', 'queue.view'),
    ('Receptionist', 'queue.manage'),
    ('Receptionist', 'audit.self'),
    ('Lab Technician', 'patient.view'),
    ('Lab Technician', 'order.view'),
    ('Lab Technician', 'lab.result.view'),
    ('Lab Technician', 'lab.result.encode'),
    ('Lab Technician', 'lab.result.validate'),
    ('Lab Technician', 'lab.specimen.receive'),
    ('Lab Technician', 'lab.critical.view'),
    ('Lab Technician', 'lab.critical.acknowledge'),
    ('Lab Technician', 'audit.self'),
    ('Med-Tech', 'patient.view'),
    ('Med-Tech', 'order.view'),
    ('Med-Tech', 'lab.result.view'),
    ('Med-Tech', 'lab.result.encode'),
    ('Med-Tech', 'lab.result.validate'),
    ('Med-Tech', 'lab.result.approve'),
    ('Med-Tech', 'lab.result.release'),
    ('Med-Tech', 'lab.result.amend.request'),
    ('Med-Tech', 'lab.specimen.receive'),
    ('Med-Tech', 'lab.critical.view'),
    ('Med-Tech', 'lab.critical.acknowledge'),
    ('Med-Tech', 'lab.critical.escalate'),
    ('Med-Tech', 'audit.self'),
    ('Pharmacist', 'patient.view'),
    ('Pharmacist', 'order.view'),
    ('Pharmacist', 'inventory.item.view'),
    ('Pharmacist', 'inventory.item.create'),
    ('Pharmacist', 'inventory.item.update'),
    ('Pharmacist', 'inventory.stock.receive'),
    ('Pharmacist', 'inventory.stock.dispense'),
    ('Pharmacist', 'inventory.adjust.request'),
    ('Pharmacist', 'audit.self'),
    ('HR Staff', 'hr.employee.view'),
    ('HR Staff', 'hr.employee.manage'),
    ('HR Staff', 'hr.employee.status.change'),
    ('HR Staff', 'hr.leave.request.view'),
    ('HR Staff', 'hr.leave.request.approve'),
    ('HR Staff', 'hr.leave.request.create_own'),
    ('HR Staff', 'audit.self'),
    ('HR Manager', 'hr.employee.view'),
    ('HR Manager', 'hr.employee.manage'),
    ('HR Manager', 'hr.employee.status.change'),
    ('HR Manager', 'hr.payroll.view'),
    ('HR Manager', 'hr.leave.request.view'),
    ('HR Manager', 'hr.leave.request.approve'),
    ('HR Manager', 'hr.leave.request.create_own'),
    ('HR Manager', 'report.export'),
    ('HR Manager', 'audit.self'),
    ('Procurement Agent', 'procurement.request.view'),
    ('Procurement Agent', 'procurement.request.create'),
    ('Procurement Agent', 'procurement.supplier.view'),
    ('Procurement Agent', 'procurement.rfq.view'),
    ('Procurement Agent', 'procurement.quote.view'),
    ('Procurement Agent', 'procurement.po.view'),
    ('Procurement Agent', 'procurement.receiving.post'),
    ('Procurement Agent', 'procurement.vendor.performance.view'),
    ('Procurement Agent', 'inventory.item.view'),
    ('Procurement Agent', 'audit.self'),
    ('Procurement Officer', 'procurement.request.view'),
    ('Procurement Officer', 'procurement.request.create'),
    ('Procurement Officer', 'procurement.supplier.view'),
    ('Procurement Officer', 'procurement.supplier.manage'),
    ('Procurement Officer', 'procurement.rfq.view'),
    ('Procurement Officer', 'procurement.quote.view'),
    ('Procurement Officer', 'procurement.po.view'),
    ('Procurement Officer', 'procurement.po.create'),
    ('Procurement Officer', 'procurement.receiving.post'),
    ('Procurement Officer', 'procurement.vendor.performance.view'),
    ('Procurement Officer', 'inventory.item.view'),
    ('Procurement Officer', 'audit.self'),
    ('Procurement Manager', 'procurement.request.view'),
    ('Procurement Manager', 'procurement.request.create'),
    ('Procurement Manager', 'procurement.request.approve'),
    ('Procurement Manager', 'procurement.supplier.view'),
    ('Procurement Manager', 'procurement.supplier.manage'),
    ('Procurement Manager', 'procurement.rfq.view'),
    ('Procurement Manager', 'procurement.quote.view'),
    ('Procurement Manager', 'procurement.po.view'),
    ('Procurement Manager', 'procurement.po.create'),
    ('Procurement Manager', 'procurement.receiving.post'),
    ('Procurement Manager', 'procurement.vendor.performance.view'),
    ('Procurement Manager', 'inventory.item.view'),
    ('Procurement Manager', 'report.export'),
    ('Procurement Manager', 'audit.self'),
    ('IT Support', 'it.system.view'),
    ('IT Support', 'it.support.manage'),
    ('IT Support', 'it.ticket.view'),
    ('IT Support', 'it.ticket.manage'),
    ('IT Support', 'notification.view'),
    ('IT Support', 'notification.manage'),
    ('IT Support', 'integration.view'),
    ('IT Support', 'audit.view'),
    ('IT Support', 'audit.self'),
    ('Compliance Officer', 'compliance.audit.review'),
    ('Compliance Officer', 'compliance.phi.monitor'),
    ('Compliance Officer', 'compliance.report.export'),
    ('Compliance Officer', 'audit.view'),
    ('Compliance Officer', 'audit.self'),
    ('Compliance Officer', 'audit.export'),
    ('Compliance Officer', 'report.export'),
    ('Compliance Officer', 'notification.view'),
    ('Field Technician', 'field_service.manage'),
    ('Field Technician', 'field_service.job.view'),
    ('Field Technician', 'field_service.job.update'),
    ('Field Technician', 'field_service.installation.update'),
    ('Field Technician', 'field_service.delivery.proof_create'),
    ('Field Technician', 'field_service.maintenance.update'),
    ('Field Technician', 'audit.self'),
    ('Field Technician', 'notification.view'),
    ('Logistics Staff', 'field_service.manage'),
    ('Logistics Staff', 'field_service.job.view'),
    ('Logistics Staff', 'field_service.job.update'),
    ('Logistics Staff', 'field_service.installation.update'),
    ('Logistics Staff', 'field_service.delivery.proof_create'),
    ('Logistics Staff', 'field_service.maintenance.update'),
    ('Logistics Staff', 'audit.self'),
    ('Logistics Staff', 'notification.view'),
    ('Logistics Staff', 'fulfillment.view'),
    ('Logistics Staff', 'fulfillment.update_status'),
    ('Service Manager', 'field_service.manage'),
    ('Service Manager', 'field_service.job.view'),
    ('Service Manager', 'field_service.job.update'),
    ('Service Manager', 'field_service.installation.update'),
    ('Service Manager', 'field_service.delivery.proof_create'),
    ('Service Manager', 'field_service.maintenance.update'),
    ('Service Manager', 'audit.self'),
    ('Service Manager', 'notification.view'),
    ('Service Manager', 'field_service.job.assign'),
    ('Service Manager', 'fulfillment.view'),
    ('Service Manager', 'fulfillment.update_status'),
    ('Service Manager', 'report.export'),
    ('Marketplace Buyer', 'marketplace.buyer'),
    ('Marketplace Buyer', 'marketplace.buyer.view'),
    ('Marketplace Buyer', 'audit.self'),
    ('Customer', 'marketplace.buyer'),
    ('Customer', 'marketplace.buyer.view'),
    ('Customer', 'audit.self'),
    ('Supplier', 'marketplace.supplier'),
    ('Supplier', 'marketplace.supplier.view'),
    ('Supplier', 'marketplace.supplier.manage_listing'),
    ('Supplier', 'audit.self'),
    ('Supplier Admin', 'marketplace.supplier'),
    ('Supplier Admin', 'marketplace.supplier.view'),
    ('Supplier Admin', 'marketplace.supplier.manage_listing'),
    ('Supplier Admin', 'audit.self'),
    ('Marketplace Supplier', 'marketplace.supplier'),
    ('Marketplace Supplier', 'marketplace.supplier.view'),
    ('Marketplace Supplier', 'marketplace.supplier.manage_listing'),
    ('Marketplace Supplier', 'audit.self'),
    ('Marketplace Admin', 'marketplace.admin'),
    ('Marketplace Admin', 'marketplace.admin.view'),
    ('Marketplace Admin', 'marketplace.admin.manage'),
    ('Marketplace Admin', 'integration.view'),
    ('Marketplace Admin', 'audit.self'),
    ('Patient', 'patient.self_service'),
    ('Patient', 'patient.portal.view_own'),
    ('Patient', 'patient.portal.appointment.view'),
    ('Patient', 'patient.portal.result.view'),
    ('Patient', 'patient.portal.billing.view'),
    ('Patient', 'patient.portal.message'),
    ('Patient', 'audit.self')
) AS assignment(role_name, permission_name)
JOIN "roles" AS role
  ON role."name" = assignment.role_name
JOIN "permissions" AS permission
  ON permission."tenant_id" = role."tenant_id"
 AND permission."name" = assignment.permission_name
ON CONFLICT ("role_id", "permission_id") DO NOTHING;
