import {
  Injectable,
  NotFoundException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { AttachDiagnosisDto } from './dto/clinical.dto';
import { EncounterStatus } from '@prisma/client';

@Injectable()
export class DiagnosisService {
  private readonly logger = new Logger(DiagnosisService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
  ) {}

  async attachDiagnosis(
    tenantId: string,
    userId: string,
    branchId: string,
    encounterId: string,
    dto: AttachDiagnosisDto,
  ) {
    try {
      const encounter = await this.prisma.encounter.findFirst({
        where: { id: encounterId, tenantId, branchId },
      });

      if (!encounter) {
        throw new NotFoundException('Encounter not found');
      }

      if (encounter.status !== EncounterStatus.OPEN) {
        throw new ConflictException(
          'clinical_encounter_not_open: Cannot attach diagnosis to a closed or cancelled encounter',
        );
      }

      return await this.prisma.$transaction(async (tx) => {
        let icd10 = await tx.icd10Code.findUnique({
          where: { code: dto.icd10Code },
        });

        if (!icd10) {
          icd10 = await tx.icd10Code.create({
            data: {
              code: dto.icd10Code,
              description: `Autogenerated description for ${dto.icd10Code}`,
            },
          });
        }

        const diagnosis = await tx.encounterDiagnosis.create({
          data: {
            encounterId,
            icd10CodeId: icd10.id,
            isPrimary: dto.isPrimary || false,
            notes: dto.notes,
          },
          include: {
            icd10Code: true,
          },
        });

        await this.audit.log(
          {
            tenantId,
            userId,
            eventKey: 'CLINICAL_DIAGNOSIS_ATTACHED',
            recordType: 'EncounterDiagnosis',
            recordId: diagnosis.id,
            newValues: {
              encounterId,
              icd10CodeId: icd10.id,
              isPrimary: diagnosis.isPrimary,
            },
          },
          tx,
          branchId,
        );

        return diagnosis;
      });
    } catch (error) {
      if (
        error instanceof NotFoundException ||
        error instanceof ConflictException
      ) {
        throw error;
      }
      this.logger.error(
        `Error in attachDiagnosis: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  async removeDiagnosis(
    tenantId: string,
    userId: string,
    encounterId: string,
    diagnosisId: string,
    reason?: string,
    branchId?: string,
  ) {
    try {
      const encounter = await this.prisma.encounter.findFirst({
        where: { id: encounterId, tenantId, branchId },
      });

      if (!encounter) {
        throw new NotFoundException('Encounter not found');
      }

      if (encounter.status !== EncounterStatus.OPEN) {
        throw new ConflictException(
          'clinical_encounter_not_open: Cannot remove diagnosis from a closed or cancelled encounter',
        );
      }

      const diagnosis = await this.prisma.encounterDiagnosis.findFirst({
        where: { id: diagnosisId, encounterId, deletedAt: null },
      });

      if (!diagnosis) {
        throw new NotFoundException('Encounter diagnosis not found');
      }

      return await this.prisma.$transaction(async (tx) => {
        await tx.encounterDiagnosis.update({
          where: { id: diagnosisId },
          data: {
            deletedAt: new Date(),
            deletedById: userId,
            deleteReason: reason ?? 'administrative_removal',
          },
        });

        await this.audit.log(
          {
            tenantId,
            userId,
            eventKey: 'CLINICAL_DIAGNOSIS_REMOVED',
            recordType: 'EncounterDiagnosis',
            recordId: diagnosisId,
            oldValues: {
              encounterId,
              icd10CodeId: diagnosis.icd10CodeId,
            },
          },
          tx,
          encounter.branchId,
        );

        return { success: true };
      });
    } catch (error) {
      if (
        error instanceof NotFoundException ||
        error instanceof ConflictException
      ) {
        throw error;
      }
      this.logger.error(
        `Error in removeDiagnosis: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  async restore(diagnosisId: string, userId: string) {
    return this.prisma.encounterDiagnosis.update({
      where: { id: diagnosisId },
      data: { deletedAt: null, deletedById: null, deleteReason: null },
    });
  }
}
