export const AUDIT_EVENT_KEYS = {
  // ── Admin & User Management ──
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ROLE_CREATED: 'ROLE_CREATED',
  PRIVILEGED_ROLE_CHANGE_GRANTED: 'PRIVILEGED_ROLE_CHANGE_GRANTED',
  PRIVILEGED_ROLE_CHANGE_REVOKED: 'PRIVILEGED_ROLE_CHANGE_REVOKED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  LOGIN_LOCKOUT: 'LOGIN_LOCKOUT',
  MFA_RECOVERY_CODE_REGENERATED: 'MFA_RECOVERY_CODE_REGENERATED',
  MFA_DISABLED: 'MFA_DISABLED',

  // ── Clinical & Patient ──
  VITALS_SAVED: 'VITALS_SAVED',
  TRIAGE_SAVED: 'TRIAGE_SAVED',
  SOAP_CREATED: 'SOAP_CREATED',
  SOAP_SIGNED: 'SOAP_SIGNED',
  CLINICAL_ORDER_CREATED: 'CLINICAL_ORDER_CREATED',
  CLINICAL_ORDER_CANCELLED: 'CLINICAL_ORDER_CANCELLED',
  LAB_ORDER_RECEIVED: 'LAB_ORDER_RECEIVED',
  LAB_RESULT_SAVED: 'LAB_RESULT_SAVED',
  LAB_RESULT_VALIDATED: 'LAB_RESULT_VALIDATED',
  LAB_RESULT_RELEASED: 'LAB_RESULT_RELEASED',
  CLINICAL_NOTE_CREATED: 'CLINICAL_NOTE_CREATED',
  CLINICAL_DIAGNOSIS_ADDED: 'CLINICAL_DIAGNOSIS_ADDED',
  PATIENT_MERGE_REQUESTED: 'PATIENT_MERGE_REQUESTED',
  PATIENT_MERGE_EXECUTED: 'PATIENT_MERGE_EXECUTED',
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',

  // ── Pharmacy ──
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  MEDICATION_DISPENSED: 'MEDICATION_DISPENSED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',

  // ── Billing & Payments ──
  PAYMENT_POSTED: 'PAYMENT_POSTED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_APPLIED: 'REFUND_APPLIED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  PAYMENT_VOID_REQUESTED: 'PAYMENT_VOID_REQUESTED',
  PAYMENT_VOID_APPLIED: 'PAYMENT_VOID_APPLIED',
  PAYMENT_VOID_REJECTED: 'PAYMENT_VOID_REJECTED',
  SESSION_OPENED: 'SESSION_OPENED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  RECEIPT_PRINTED: 'RECEIPT_PRINTED',
  RECEIPT_REPRINTED: 'RECEIPT_REPRINTED',
  RECEIPT_EXPORTED: 'RECEIPT_EXPORTED',
  PAYMENT_GATEWAY_CONFIRMED: 'PAYMENT_GATEWAY_CONFIRMED',
  RECONCILIATION_PERFORMED: 'RECONCILIATION_PERFORMED',

  // ── Invoices ──
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_PDF_EXPORTED: 'INVOICE_PDF_EXPORTED',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',

  // ── Catalog ──
  CATALOG_CATEGORY_CREATED: 'CATALOG_CATEGORY_CREATED',
  CATALOG_ITEM_CREATED: 'CATALOG_ITEM_CREATED',
  SERVICE_PRICE_UPDATED: 'SERVICE_PRICE_UPDATED',

  // ── Access & Security ──
  SENSITIVE_ACCESS_GRANTED: 'SENSITIVE_ACCESS_GRANTED',
  SENSITIVE_ACCESS_BLOCKED: 'SENSITIVE_ACCESS_BLOCKED',
  READ_ACCESS_AUDITED: 'READ_ACCESS_AUDITED',
  BREAK_GLASS_ACTIVATED: 'BREAK_GLASS_ACTIVATED',
  BREAK_GLASS_JUSTIFIED: 'BREAK_GLASS_JUSTIFIED',
  SECURITY_BREACH_DETECTED: 'SECURITY_BREACH_DETECTED',

  // ── Export / Download ──
  FILE_DOWNLOADED: 'FILE_DOWNLOADED',
  LAB_RESULT_PDF_EXPORTED: 'LAB_RESULT_PDF_EXPORTED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  AUDIT_LOG_EXPORTED: 'AUDIT_LOG_EXPORTED',

  // ── Retention / Archival ──
  AUDIT_LOG_RETENTION_ENFORCED: 'AUDIT_LOG_RETENTION_ENFORCED',
  AUDIT_LOG_ARCHIVED: 'AUDIT_LOG_ARCHIVED',

  // ── Chain / Integrity ──
  CHAIN_VERIFICATION_RUN: 'CHAIN_VERIFICATION_RUN',
  CHAIN_CORRUPTION_DETECTED: 'CHAIN_CORRUPTION_DETECTED',
} as const;

export type AuditEventKey =
  (typeof AUDIT_EVENT_KEYS)[keyof typeof AUDIT_EVENT_KEYS];
