export type AuthorizationRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'PRIVILEGED';

export interface AuthorizationPermissionDefinition {
  name: string;
  scope: string;
  riskLevel: AuthorizationRiskLevel;
}

const permission = (
  name: string,
  scope = 'tenant/branch',
  riskLevel: AuthorizationRiskLevel = 'LOW',
): AuthorizationPermissionDefinition => ({ name, scope, riskLevel });

/**
 * Canonical tenant permission registry. Seed and tenant provisioning both consume
 * this list so a permission referenced by a route/controller cannot disappear in
 * newly-created tenants.
 */
export const AUTHORIZATION_PERMISSIONS: AuthorizationPermissionDefinition[] = [
  permission('patient.view'),
  permission('patient.create'),
  permission('patient.update'),
  permission('patient.merge.request', 'tenant', 'MEDIUM'),
  permission('patient.merge.approve', 'tenant', 'PRIVILEGED'),
  permission('patient.self_service', 'tenant/user'),
  permission('patient.portal.view_own', 'tenant/user'),
  permission('patient.portal.appointment.view', 'tenant/user'),
  permission('patient.portal.result.view', 'tenant/user'),
  permission('patient.portal.billing.view', 'tenant/user'),
  permission('patient.portal.message', 'tenant/user'),

  permission('encounter.create'),
  permission('encounter.view'),
  permission('encounter.update'),
  permission('clinical_note.create'),
  permission('doctor.prescription.view'),
  permission('doctor.prescription.create'),

  permission('queue.view'),
  permission('queue.manage'),
  permission('order.view'),
  permission('order.create'),
  permission('order.cancel', 'tenant/branch', 'MEDIUM'),

  permission('lab.result.view', 'tenant/branch/department'),
  permission('lab.result.encode', 'tenant/branch/department'),
  permission('lab.result.validate', 'tenant/branch/department', 'MEDIUM'),
  permission('lab.result.approve', 'tenant/branch/department', 'HIGH'),
  permission('lab.result.release', 'tenant/branch/department', 'HIGH'),
  permission('lab.result.amend.request', 'tenant/branch', 'MEDIUM'),
  permission('lab.specimen.receive', 'tenant/branch/department'),
  permission('lab.critical.view', 'tenant/branch/department'),
  permission('lab.critical.acknowledge', 'tenant/branch/department', 'MEDIUM'),
  permission('lab.critical.escalate', 'tenant/branch/department', 'HIGH'),

  permission('billing.invoice.view'),
  permission('billing.payment.create', 'tenant/branch/cashier-session'),
  permission('billing.refund.request', 'tenant/branch', 'MEDIUM'),
  permission('billing.refund.approve', 'tenant/branch', 'HIGH'),
  permission('billing.payment.void.request', 'tenant/branch', 'MEDIUM'),
  permission('billing.claim.view'),
  permission('billing.claim.create'),
  permission('billing.claim.process', 'tenant/branch', 'HIGH'),
  permission('billing.reversal.apply', 'tenant/branch', 'HIGH'),

  permission('inventory.item.view'),
  permission('inventory.item.create'),
  permission('inventory.item.update'),
  permission('inventory.item.deactivate', 'tenant/branch', 'MEDIUM'),
  permission('inventory.stock.receive'),
  permission('inventory.stock.dispense'),
  permission('inventory.adjust.request', 'tenant/branch', 'MEDIUM'),
  permission('inventory.adjust.approve', 'tenant/branch', 'HIGH'),

  permission('catalog.service.view', 'tenant'),
  permission('catalog.service.create', 'tenant', 'MEDIUM'),
  permission('catalog.service.update', 'tenant', 'MEDIUM'),
  permission('catalog.service.deactivate', 'tenant', 'HIGH'),
  permission('catalog.manage', 'tenant', 'MEDIUM'),

  permission('approval.request.create', 'tenant/branch', 'MEDIUM'),
  permission('approval.request.view', 'tenant/branch', 'MEDIUM'),
  permission('approval.request.process', 'tenant/branch', 'HIGH'),

  permission('report.export', 'tenant/branch/role-scope', 'HIGH'),
  permission('audit.view', 'tenant/branch/role-scope', 'HIGH'),
  permission('audit.self', 'tenant/user', 'LOW'),
  permission('audit.export', 'tenant/branch/role-scope', 'HIGH'),

  permission('admin.health.view', 'tenant', 'HIGH'),
  permission('admin.metrics.view', 'tenant', 'HIGH'),
  permission('admin.user.view', 'tenant', 'HIGH'),
  permission('admin.branch.view', 'tenant', 'HIGH'),
  permission('admin.role.change', 'tenant/system', 'PRIVILEGED'),

  permission('notification.view', 'tenant/user'),
  permission('notification.manage', 'tenant/branch', 'MEDIUM'),
  permission('integration.view', 'tenant'),

  permission('compliance.audit.review', 'tenant', 'HIGH'),
  permission('compliance.phi.monitor', 'tenant', 'HIGH'),
  permission('compliance.report.export', 'tenant', 'HIGH'),

  permission('it.system.view', 'tenant'),
  permission('it.support.manage', 'tenant', 'MEDIUM'),
  permission('it.ticket.view', 'tenant'),
  permission('it.ticket.manage', 'tenant', 'MEDIUM'),

  permission('hr.employee.view', 'tenant/branch'),
  permission('hr.employee.manage', 'tenant/branch', 'MEDIUM'),
  permission('hr.payroll.view', 'tenant/branch', 'HIGH'),

  permission('procurement.request.view'),
  permission('procurement.request.create'),
  permission('procurement.request.approve', 'tenant/branch', 'HIGH'),
  permission('procurement.supplier.view'),
  permission('procurement.supplier.manage', 'tenant', 'MEDIUM'),
  permission('procurement.rfq.view'),
  permission('procurement.quote.view'),
  permission('procurement.po.view'),
  permission('procurement.po.create', 'tenant/branch', 'MEDIUM'),
  permission('procurement.receiving.post', 'tenant/branch', 'MEDIUM'),
  permission('procurement.vendor.performance.view'),

  // Legacy aliases remain provisioned while the UI/backend migrate to granular keys.
  permission('marketplace.buyer', 'tenant'),
  permission('marketplace.supplier', 'tenant'),
  permission('marketplace.admin', 'tenant', 'HIGH'),
  permission('marketplace.buyer.view', 'tenant'),
  permission('marketplace.supplier.view', 'tenant'),
  permission('marketplace.supplier.manage_listing', 'tenant', 'MEDIUM'),
  permission('marketplace.admin.view', 'tenant', 'HIGH'),
  permission('marketplace.admin.manage', 'tenant', 'HIGH'),

  permission('field_service.manage', 'tenant/branch', 'MEDIUM'),
  permission('field_service.job.view'),
  permission('field_service.job.update', 'tenant/branch', 'MEDIUM'),
  permission('field_service.job.assign', 'tenant/branch', 'MEDIUM'),
  permission('field_service.installation.update', 'tenant/branch', 'MEDIUM'),
  permission('field_service.delivery.proof_create', 'tenant/branch', 'MEDIUM'),
  permission('field_service.maintenance.update', 'tenant/branch', 'MEDIUM'),
  permission('fulfillment.view'),
  permission('fulfillment.update_status', 'tenant/branch', 'MEDIUM'),
];

const clinicalBase = [
  'patient.view',
  'patient.create',
  'patient.update',
  'encounter.create',
  'encounter.view',
  'encounter.update',
  'queue.view',
  'order.view',
  'audit.self',
  'notification.view',
];

const fieldServiceBase = [
  'field_service.manage',
  'field_service.job.view',
  'field_service.job.update',
  'field_service.installation.update',
  'field_service.delivery.proof_create',
  'field_service.maintenance.update',
  'audit.self',
  'notification.view',
];

/** Built-in immutable roles. Non-privileged system roles are assignable to users. */
export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
  'Super Admin': AUTHORIZATION_PERMISSIONS.map(({ name }) => name),
  'Branch Admin': [
    ...clinicalBase,
    'queue.manage',
    'order.create',
    'order.cancel',
    'lab.result.view',
    'lab.result.encode',
    'lab.result.validate',
    'lab.result.approve',
    'lab.result.release',
    'lab.specimen.receive',
    'lab.critical.view',
    'billing.invoice.view',
    'billing.payment.create',
    'billing.refund.request',
    'billing.payment.void.request',
    'billing.claim.view',
    'billing.claim.create',
    'inventory.item.view',
    'inventory.item.create',
    'inventory.item.update',
    'inventory.stock.receive',
    'inventory.stock.dispense',
    'inventory.adjust.request',
    'catalog.service.view',
    'approval.request.create',
    'approval.request.view',
    'approval.request.process',
    'report.export',
    'audit.view',
    'hr.employee.view',
    'hr.employee.manage',
    'procurement.request.view',
    'procurement.request.create',
    'procurement.supplier.view',
    'procurement.rfq.view',
    'procurement.quote.view',
    'procurement.po.view',
    'procurement.receiving.post',
    'procurement.vendor.performance.view',
    ...fieldServiceBase,
    'field_service.job.assign',
    'fulfillment.view',
    'fulfillment.update_status',
    'integration.view',
    'admin.user.view',
    'admin.branch.view',
  ],
  Doctor: [
    ...clinicalBase,
    'queue.manage',
    'order.create',
    'lab.result.view',
    'clinical_note.create',
    'doctor.prescription.view',
    'doctor.prescription.create',
  ],
  Nurse: [
    ...clinicalBase,
    'queue.manage',
    'order.create',
    'lab.result.view',
    'lab.specimen.receive',
    'lab.critical.view',
  ],
  Cashier: [
    'patient.view',
    'order.view',
    'billing.invoice.view',
    'billing.payment.create',
    'billing.refund.request',
    'billing.payment.void.request',
    'billing.claim.view',
    'billing.claim.create',
    'approval.request.create',
    'approval.request.view',
    'audit.self',
    'notification.view',
  ],
  Finance: [
    'patient.view',
    'order.view',
    'billing.invoice.view',
    'billing.payment.create',
    'billing.refund.request',
    'billing.refund.approve',
    'billing.payment.void.request',
    'billing.claim.view',
    'billing.claim.create',
    'billing.claim.process',
    'billing.reversal.apply',
    'approval.request.view',
    'approval.request.process',
    'report.export',
    'audit.self',
  ],
  Receptionist: [
    'patient.view',
    'patient.create',
    'patient.update',
    'queue.view',
    'queue.manage',
    'audit.self',
  ],
  'Lab Technician': [
    'patient.view',
    'order.view',
    'lab.result.view',
    'lab.result.encode',
    'lab.result.validate',
    'lab.specimen.receive',
    'lab.critical.view',
    'lab.critical.acknowledge',
    'audit.self',
  ],
  'Med-Tech': [
    'patient.view',
    'order.view',
    'lab.result.view',
    'lab.result.encode',
    'lab.result.validate',
    'lab.result.approve',
    'lab.result.release',
    'lab.result.amend.request',
    'lab.specimen.receive',
    'lab.critical.view',
    'lab.critical.acknowledge',
    'lab.critical.escalate',
    'audit.self',
  ],
  Pharmacist: [
    'patient.view',
    'order.view',
    'inventory.item.view',
    'inventory.item.create',
    'inventory.item.update',
    'inventory.stock.receive',
    'inventory.stock.dispense',
    'inventory.adjust.request',
    'audit.self',
  ],
  'HR Staff': ['hr.employee.view', 'hr.employee.manage', 'audit.self'],
  'HR Manager': [
    'hr.employee.view',
    'hr.employee.manage',
    'hr.payroll.view',
    'report.export',
    'audit.self',
  ],
  'Procurement Agent': [
    'procurement.request.view',
    'procurement.request.create',
    'procurement.supplier.view',
    'procurement.rfq.view',
    'procurement.quote.view',
    'procurement.po.view',
    'procurement.receiving.post',
    'procurement.vendor.performance.view',
    'inventory.item.view',
    'audit.self',
  ],
  'Procurement Officer': [
    'procurement.request.view',
    'procurement.request.create',
    'procurement.supplier.view',
    'procurement.supplier.manage',
    'procurement.rfq.view',
    'procurement.quote.view',
    'procurement.po.view',
    'procurement.po.create',
    'procurement.receiving.post',
    'procurement.vendor.performance.view',
    'inventory.item.view',
    'audit.self',
  ],
  'Procurement Manager': [
    'procurement.request.view',
    'procurement.request.create',
    'procurement.request.approve',
    'procurement.supplier.view',
    'procurement.supplier.manage',
    'procurement.rfq.view',
    'procurement.quote.view',
    'procurement.po.view',
    'procurement.po.create',
    'procurement.receiving.post',
    'procurement.vendor.performance.view',
    'inventory.item.view',
    'report.export',
    'audit.self',
  ],
  'IT Support': [
    'it.system.view',
    'it.support.manage',
    'it.ticket.view',
    'it.ticket.manage',
    'notification.view',
    'notification.manage',
    'integration.view',
    'audit.view',
    'audit.self',
  ],
  'Compliance Officer': [
    'compliance.audit.review',
    'compliance.phi.monitor',
    'compliance.report.export',
    'audit.view',
    'audit.self',
    'audit.export',
    'report.export',
    'notification.view',
  ],
  'Field Technician': fieldServiceBase,
  'Logistics Staff': [
    ...fieldServiceBase,
    'fulfillment.view',
    'fulfillment.update_status',
  ],
  'Service Manager': [
    ...fieldServiceBase,
    'field_service.job.assign',
    'fulfillment.view',
    'fulfillment.update_status',
    'report.export',
  ],
  'Marketplace Buyer': [
    'marketplace.buyer',
    'marketplace.buyer.view',
    'audit.self',
  ],
  Customer: ['marketplace.buyer', 'marketplace.buyer.view', 'audit.self'],
  Supplier: [
    'marketplace.supplier',
    'marketplace.supplier.view',
    'marketplace.supplier.manage_listing',
    'audit.self',
  ],
  'Supplier Admin': [
    'marketplace.supplier',
    'marketplace.supplier.view',
    'marketplace.supplier.manage_listing',
    'audit.self',
  ],
  'Marketplace Supplier': [
    'marketplace.supplier',
    'marketplace.supplier.view',
    'marketplace.supplier.manage_listing',
    'audit.self',
  ],
  'Marketplace Admin': [
    'marketplace.admin',
    'marketplace.admin.view',
    'marketplace.admin.manage',
    'integration.view',
    'audit.self',
  ],
  Patient: [
    'patient.self_service',
    'patient.portal.view_own',
    'patient.portal.appointment.view',
    'patient.portal.result.view',
    'patient.portal.billing.view',
    'patient.portal.message',
    'audit.self',
  ],
};

export const SYSTEM_ROLE_NAMES = Object.keys(SYSTEM_ROLE_PERMISSIONS);
