export const PERMISSIONS = {
  PATIENT_VIEW: 'patient.view',
  ENCOUNTER_UPDATE: 'encounter.update',
  PATIENT_CREATE: 'patient.create',
  QUEUE_VIEW: 'queue.view',
  QUEUE_MANAGE: 'queue.manage',
  LAB_RESULT_VIEW: 'lab.result.view',
  INVENTORY_DISPENSE: 'inventory.stock.dispense',
  BILLING_VIEW: 'billing.invoice.view',
  INVENTORY_VIEW: 'inventory.item.view',
  INVENTORY_RECEIVE: 'inventory.stock.receive',
  ORDER_CREATE: 'order.create',
  APPROVAL_VIEW: 'approval.request.view',
  ADMIN_ROLE_CHANGE: 'admin.role.change',
  REPORT_EXPORT: 'report.export',
  AUDIT_VIEW: 'audit.view',
  AUDIT_SELF: 'audit.self',
  AUDIT_EXPORT: 'audit.export',
  COMPLIANCE_AUDIT_REVIEW: 'compliance.audit.review',
  IT_SYSTEM_VIEW: 'it.system.view',
  INTEGRATION_VIEW: 'integration.view',
  HR_MANAGE: 'hr.employee.manage',
  PROCUREMENT_VIEW: 'procurement.request.view',
  PROCUREMENT_MANAGE: 'procurement.supplier.manage',
  PATIENT_SELF_SERVICE: 'patient.self_service',
  PATIENT_MERGE_REQUEST: 'patient.merge.request',
  PATIENT_MERGE_APPROVE: 'patient.merge.approve',
  MARKETPLACE_BUYER: 'marketplace.buyer',
  MARKETPLACE_SUPPLIER: 'marketplace.supplier',
  MARKETPLACE_ADMIN: 'marketplace.admin',
  FIELD_SERVICE_MANAGE: 'field_service.manage',
  FIELD_SERVICE_JOB_VIEW: 'field_service.job.view',
  FIELD_SERVICE_JOB_UPDATE: 'field_service.job.update',
  FIELD_SERVICE_JOB_ASSIGN: 'field_service.job.assign',
  FIELD_SERVICE_INSTALLATION_UPDATE: 'field_service.installation.update',
  FIELD_SERVICE_DELIVERY_PROOF_CREATE: 'field_service.delivery.proof_create',
  FIELD_SERVICE_MAINTENANCE_UPDATE: 'field_service.maintenance.update',
  FULFILLMENT_VIEW: 'fulfillment.view',
  FULFILLMENT_UPDATE_STATUS: 'fulfillment.update_status',
  NOTIFICATION_VIEW: 'notification.view',
  NOTIFICATION_MANAGE: 'notification.manage',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
