import {
  Activity,
  AlertOctagon,
  BarChart3,
  Bell,
  Box,
  Briefcase,
  Building,
  Calendar,
  CheckCircle2,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  FileBadge,
  FilePlus,
  FileText,
  FlaskConical,
  GitMerge,
  History,
  Inbox,
  Key,
  LayoutDashboard,
  LifeBuoy,
  Link2,
  ListOrdered,
  Map,
  MessageSquare,
  Package,
  PackageCheck,
  Pill,
  Play,
  PlusCircle,
  Scale,
  Send,
  SettingsIcon,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Stethoscope,
  Terminal,
  TrendingUp,
  Trophy,
  Truck,
  UserCircle,
  UserX,
  Users,
  Video,
  Wrench
} from 'lucide-react';
import { PERMISSIONS } from './permissions';

export interface NavItemConfig {
  label: string;
  to: string;
  icon: React.ElementType;
  permission?: string;
  allowedRoles?: string[];
  isBranchScoped?: boolean;
  zone?: 'staff' | 'patient' | 'marketplace' | 'public';
}

export interface NavGroupConfig {
  label: string;
  items: NavItemConfig[];
}

export const roleNavigation: NavGroupConfig[] = [
  {
    label: 'SuperAdmin Workspace',
    items: [
      { label: 'SuperAdmin Dashboard', to: '/admin', icon: LayoutDashboard, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Tenants Manager', to: '/admin/tenants', icon: Building, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Branches Manager', to: '/admin/branches', icon: GitMerge, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Users & Accounts', to: '/admin/users', icon: Users, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Roles & Permissions', to: '/admin/roles-permissions', icon: ShieldCheck, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Security Center', to: '/admin/security', icon: ShieldAlert, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'System Audit Logs', to: '/admin/audit-logs', icon: History, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Global Settings', to: '/admin/settings', icon: SettingsIcon, allowedRoles: ['Super Admin'], zone: 'staff' },
      { label: 'Reports & Metrics', to: '/admin/reports', icon: BarChart3, allowedRoles: ['Super Admin'], zone: 'staff' },
    ],
  },
  {
    label: 'Compliance Workspace',
    items: [
      { label: 'Compliance Dashboard', to: '/compliance', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'PHI Access Monitor', to: '/compliance/phi-access', icon: Activity, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Audit Log Review', to: '/compliance/audit-review', icon: ClipboardList, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Access Reviews', to: '/compliance/access-reviews', icon: Users, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Data Export Logs', to: '/compliance/export-logs', icon: History, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Breach Incidents', to: '/compliance/breach-alerts', icon: ShieldAlert, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Data Retention', to: '/compliance/retention', icon: Package, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Compliance Reports', to: '/compliance/reports', icon: FileText, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
      { label: 'Audit Chain Verification', to: '/compliance/audit-chain', icon: CheckSquare, allowedRoles: ['Super Admin', 'Compliance Officer'], zone: 'staff' },
    ],
  },
  {
    label: 'IT Workspace',
    items: [
      { label: 'IT Support Dashboard', to: '/it', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'System Health Monitor', to: '/it/system-health', icon: Cpu, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'User Support Queue', to: '/it/user-support', icon: LifeBuoy, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'Active User Sessions', to: '/it/sessions', icon: Key, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'Background Job Monitor', to: '/it/background-jobs', icon: Play, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'System Integrations', to: '/it/integrations', icon: Link2, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'System Audit Logs', to: '/it/logs', icon: Terminal, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'Backup & Recovery', to: '/it/backup-restore', icon: Database, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
      { label: 'Incident Desk', to: '/it/incidents', icon: AlertOctagon, allowedRoles: ['Super Admin', 'IT Support'], zone: 'staff' },
    ],
  },
  {
    label: 'HR Workspace',
    items: [
      { label: 'HR Dashboard', to: '/hr', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Employee Directory', to: '/hr/employees', icon: Users, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Department Manager', to: '/hr/departments', icon: Building, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Attendance Tracking', to: '/hr/attendance', icon: Clock, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Leave Management', to: '/hr/leave', icon: Calendar, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Payroll Console', to: '/hr/payroll', icon: DollarSign, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Licenses & Certs', to: '/hr/licenses', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Branch Assignments', to: '/hr/branch-assignments', icon: GitMerge, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
      { label: 'Termination Desk', to: '/hr/termination', icon: UserX, allowedRoles: ['Super Admin', 'Branch Admin', 'HR Manager'], zone: 'staff' },
    ],
  },
  {
    label: 'Procurement Workspace',
    items: [
      { label: 'Procurement Dashboard', to: '/procurement', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Supplier Directory', to: '/procurement/suppliers', icon: Truck, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Purchase Requests', to: '/procurement/purchase-requests', icon: FilePlus, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'RFQ Manager', to: '/procurement/rfqs', icon: Send, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Quotes & Bids', to: '/procurement/quotes', icon: DollarSign, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Purchase Orders', to: '/procurement/purchase-orders', icon: ShoppingBag, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Receiving Dock', to: '/procurement/receiving', icon: PackageCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Inventory Requests', to: '/procurement/inventory-requests', icon: Inbox, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
      { label: 'Vendor Performance', to: '/procurement/vendor-performance', icon: Trophy, allowedRoles: ['Super Admin', 'Branch Admin', 'Procurement Manager', 'Procurement Agent'], zone: 'staff' },
    ],
  },
  {
    label: 'Pharmacy Workspace',
    items: [
      { label: 'Pharmacy Dashboard', to: '/pharmacy', icon: LayoutDashboard, permission: PERMISSIONS.INVENTORY_DISPENSE, allowedRoles: ['Super Admin', 'Branch Admin', 'Pharmacist'], zone: 'staff', isBranchScoped: true },
      { label: 'Dispense Queue', to: '/pharmacy/dispense', icon: Pill, permission: PERMISSIONS.INVENTORY_DISPENSE, allowedRoles: ['Super Admin', 'Branch Admin', 'Pharmacist'], zone: 'staff', isBranchScoped: true },
      { label: 'Drug Inventory', to: '/pharmacy/inventory', icon: Package, permission: PERMISSIONS.INVENTORY_VIEW, allowedRoles: ['Super Admin', 'Branch Admin', 'Pharmacist'], zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Marketplace (Buyer)',
    items: [
      { label: 'Marketplace Home', to: '/marketplace', icon: ShoppingCart, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'Product Catalog', to: '/marketplace/products', icon: Box, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'My RFQs', to: '/marketplace/rfqs', icon: FileText, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'Track Orders', to: '/marketplace/orders', icon: Package, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'Installations', to: '/marketplace/installations', icon: Wrench, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'Warranties', to: '/marketplace/warranty', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
      { label: 'Service Desk', to: '/marketplace/service-tickets', icon: Clock, allowedRoles: ['Super Admin', 'Branch Admin', 'Marketplace Buyer', 'Customer'], zone: 'marketplace' },
    ],
  },
  {
    label: 'Marketplace (Supplier)',
    items: [
      { label: 'Supplier Dashboard', to: '/supplier', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Product Listings', to: '/supplier/listings', icon: Package, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Service Offerings', to: '/supplier/service-listings', icon: Wrench, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'RFQ Inbox', to: '/supplier/rfq-inbox', icon: FileText, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'My Quotes', to: '/supplier/quotes', icon: DollarSign, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Manage Orders', to: '/supplier/orders', icon: ShoppingBag, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Fulfillment Dock', to: '/supplier/fulfillment', icon: Truck, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Warranty Claims', to: '/supplier/warranty-claims', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Service Commitments', to: '/supplier/service-commitments', icon: Clock, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Payouts & Ledger', to: '/supplier/payouts', icon: DollarSign, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
      { label: 'Performance', to: '/supplier/performance', icon: Trophy, allowedRoles: ['Super Admin', 'Branch Admin', 'Supplier', 'Supplier Admin', 'Marketplace Supplier'], zone: 'marketplace' },
    ],
  },
  {
    label: 'Marketplace (Admin)',
    items: [
      { label: 'Admin Dashboard', to: '/marketplace-admin', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Supplier Management', to: '/marketplace-admin/suppliers', icon: Users, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Buyer Management', to: '/marketplace-admin/buyers', icon: UserCircle, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Listing Approval', to: '/marketplace-admin/listing-approval', icon: PackageCheck, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'RFQ Monitor', to: '/marketplace-admin/rfq-monitor', icon: Send, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Order Monitor', to: '/marketplace-admin/order-monitor', icon: ShoppingBag, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Fulfillment Monitor', to: '/marketplace-admin/fulfillment-monitor', icon: Truck, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Installation Monitor', to: '/marketplace-admin/installation-monitor', icon: Wrench, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Warranty Claims', to: '/marketplace-admin/warranty-claims', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Disputes', to: '/marketplace-admin/disputes', icon: AlertOctagon, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Commission & Fees', to: '/marketplace-admin/commission-fees', icon: DollarSign, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
      { label: 'Reports', to: '/marketplace-admin/reports', icon: BarChart3, allowedRoles: ['Super Admin', 'Marketplace Admin'], zone: 'marketplace' },
    ],
  },
  {
    label: 'Field Service (Logistics)',
    items: [
      { label: 'Service Dashboard', to: '/field-service', icon: LayoutDashboard, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Delivery Jobs', to: '/field-service/deliveries', icon: Truck, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Installations', to: '/field-service/installations', icon: Wrench, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'My Schedule', to: '/field-service/schedule', icon: Calendar, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Handover Checklists', to: '/field-service/handover', icon: ClipboardCheck, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Proof of Delivery', to: '/field-service/proof-of-delivery', icon: FileBadge, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Warranty Activation', to: '/field-service/warranty-activation', icon: ShieldCheck, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Preventive Maintenance', to: '/field-service/preventive-maintenance', icon: SettingsIcon, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Service Worklog', to: '/field-service/service-worklog', icon: FileText, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
      { label: 'Offline Sync', to: '/field-service/offline-sync', icon: GitMerge, permission: PERMISSIONS.FIELD_SERVICE_MANAGE, zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Integration Bridges',
    items: [
      { label: 'Integration Dashboard', to: '/integration', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Notification Center', to: '/integration/notifications', icon: Bell, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Approval Center', to: '/integration/approvals', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Global Search', to: '/integration/global-search', icon: BarChart3, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Patient Timeline', to: '/integration/patient-timeline', icon: Users, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Asset Timeline', to: '/integration/asset-timeline', icon: Package, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Reconciliation Monitor', to: '/integration/reconciliation', icon: TrendingUp, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
      { label: 'Activity & Audit', to: '/integration/activity-audit', icon: Activity, allowedRoles: ['Super Admin', 'Marketplace Admin', 'Branch Admin'], zone: 'staff' },
    ],
  },
  {
    label: 'Patient Workspace',
    items: [
      { label: 'My Dashboard', to: '/patient', icon: LayoutDashboard, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Appointments', to: '/patient/appointments', icon: Calendar, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Lab Results', to: '/patient/lab-results', icon: FlaskConical, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Prescriptions', to: '/patient/prescriptions', icon: Pill, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Billing & Payments', to: '/patient/billing', icon: CreditCard, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Medical Records', to: '/patient/medical-records', icon: FileBadge, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'Messages', to: '/patient/messages', icon: MessageSquare, allowedRoles: ['Patient'], zone: 'patient' },
      { label: 'My Profile', to: '/patient/profile', icon: UserCircle, allowedRoles: ['Patient'], zone: 'patient' },
    ],
  },
  {
    label: 'Doctor Workspace',
    items: [
      { label: 'Doctor Dashboard', to: '/doctor', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Doctor'], zone: 'staff', isBranchScoped: true },
      { label: 'Patient Queue', to: '/doctor/queue', icon: ListOrdered, allowedRoles: ['Super Admin', 'Branch Admin', 'Doctor'], zone: 'staff', isBranchScoped: true },
      { label: 'Patient Directory', to: '/doctor/patients', icon: Users, allowedRoles: ['Super Admin', 'Branch Admin', 'Doctor'], zone: 'staff', isBranchScoped: true },
      { label: 'EMR Charting', to: '/doctor/emr', icon: Stethoscope, allowedRoles: ['Super Admin', 'Branch Admin', 'Doctor'], zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Nurse Workspace',
    items: [
      { label: 'Nurse Dashboard', to: '/nurse', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
      { label: 'Triage Queue', to: '/nurse/triage', icon: ListOrdered, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
      { label: 'Patient Intake', to: '/nurse/intake', icon: PlusCircle, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
      { label: 'Vitals Logging', to: '/nurse/vitals', icon: Activity, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
      { label: 'Nursing Tasks', to: '/nurse/tasks', icon: CheckSquare, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
      { label: 'Specimen Collection', to: '/nurse/specimens', icon: FlaskConical, allowedRoles: ['Super Admin', 'Branch Admin', 'Nurse'], zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Lab Workspace',
    items: [
      { label: 'Lab Dashboard', to: '/lab', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'LIS Orders', to: '/lab/orders', icon: ListOrdered, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'Specimen Receiving', to: '/lab/specimens', icon: FlaskConical, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'Result Entry', to: '/lab/encoding', icon: FileText, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'QA Verification', to: '/lab/validation', icon: ClipboardCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'Pending Release', to: '/lab/validated', icon: Send, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'Released Results', to: '/lab/released', icon: CheckCircle2, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'Critical Alerts', to: '/lab/critical-results', icon: ShieldAlert, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
      { label: 'TAT SLA Monitor', to: '/lab/turnaround', icon: TrendingUp, allowedRoles: ['Super Admin', 'Branch Admin', 'Lab Technician'], zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Cashier Workspace',
    items: [
      { label: 'Cashier Dashboard', to: '/cashier', icon: LayoutDashboard, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'Patient Billing', to: '/cashier/billing', icon: CreditCard, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'POS Invoices', to: '/cashier/invoices', icon: FileText, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'Receipts Ledger', to: '/cashier/payments', icon: History, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'Drawer Session', to: '/cashier/session', icon: Coins, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'Voids & Refunds', to: '/cashier/refunds-voids', icon: ShieldAlert, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'HMO Claims', to: '/cashier/hmo-claims', icon: ShieldCheck, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
      { label: 'Reconciliation', to: '/cashier/reconciliation', icon: Scale, allowedRoles: ['Super Admin', 'Branch Admin', 'Cashier', 'Finance'], zone: 'staff', isBranchScoped: true },
    ],
  },

  {
    label: 'Dashboard & Core',
    items: [
      { label: 'Command Center', to: '/', icon: LayoutDashboard, zone: 'staff' },
      { label: 'Spatial Tracking', to: '/spatial', icon: Map, zone: 'staff' },
    ],
  },
  {
    label: 'Clinical Modules',
    items: [
      { label: 'Patient Management', to: '/patients', icon: Users, permission: PERMISSIONS.PATIENT_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'Appointment & Queue', to: '/queue', icon: ListOrdered, permission: PERMISSIONS.QUEUE_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'EMR / Records', to: '/emr', icon: ClipboardList, permission: PERMISSIONS.PATIENT_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'Telehealth', to: '/telehealth', icon: Video, permission: PERMISSIONS.PATIENT_VIEW, allowedRoles: ['Super Admin', 'Branch Admin', 'Doctor', 'Nurse', 'Patient'], zone: 'staff', isBranchScoped: true },
      { label: 'Laboratory / LIS', to: '/lab/results', icon: FlaskConical, permission: PERMISSIONS.LAB_RESULT_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'Radiology', to: '/radiology', icon: CheckSquare, permission: PERMISSIONS.LAB_RESULT_VIEW, zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Finance & Supply',
    items: [
      { label: 'Pharmacy', to: '/pharmacy', icon: Pill, permission: PERMISSIONS.INVENTORY_DISPENSE, zone: 'staff', isBranchScoped: true },
      { label: 'B2B Sales Summary', to: '/sales-dashboard', icon: BarChart3, zone: 'staff' },
      { label: 'Logistics & Handover', to: '/logistics-checklist', icon: Briefcase, zone: 'staff' },
      { label: 'Billing & Cashier', to: '/billing', icon: CreditCard, permission: PERMISSIONS.BILLING_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'HMO Claims', to: '/claims', icon: ShieldCheck, permission: PERMISSIONS.BILLING_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'Inventory & Procurement', to: '/inventory', icon: Package, permission: PERMISSIONS.INVENTORY_VIEW, zone: 'staff', isBranchScoped: true },
    ],
  },
  {
    label: 'Administration & Security',
    items: [
      { label: 'Products & Services', to: '/orders/new', icon: PlusCircle, permission: PERMISSIONS.ORDER_CREATE, zone: 'staff', isBranchScoped: true },
      { label: 'Approvals', to: '/approvals', icon: ClipboardCheck, permission: PERMISSIONS.APPROVAL_VIEW, zone: 'staff', isBranchScoped: true },
      { label: 'Users & Roles', to: '/admin/users', icon: Users, permission: PERMISSIONS.ADMIN_ROLE_CHANGE, allowedRoles: ['Branch Admin'], zone: 'staff' },
      { label: 'Chart Reconciliation', to: '/admin/patient-merges', icon: GitMerge, permission: PERMISSIONS.ADMIN_ROLE_CHANGE, zone: 'staff' },
      { label: 'HR Management', to: '/hr', icon: Briefcase, zone: 'staff' },
      { label: 'Reports & Analytics', to: '/reports', icon: BarChart3, permission: PERMISSIONS.REPORT_EXPORT, zone: 'staff', isBranchScoped: true },
      { label: 'Notifications', to: '/notifications', icon: Bell, zone: 'staff' },
      { label: 'Security & Audit Logs', to: '/audit-logs', icon: ShieldCheck, permission: PERMISSIONS.AUDIT_VIEW, allowedRoles: ['Branch Admin'], zone: 'staff' },
      { label: 'System Settings', to: '/settings', icon: SettingsIcon, permission: PERMISSIONS.ADMIN_ROLE_CHANGE, allowedRoles: ['Branch Admin'], zone: 'staff' },
    ],
  },
];
